[package]
name = "espressif-esp32-c6-devkitc-1"
version = "0.1.0"
license.workspace = true
edition.workspace = true

[dependencies]
ariel-os-rt = { workspace = true, features = ["_esp32c6"] }
ariel-os-debug.workspace = true
