[default.extend-words]
hax = "hax"
hsi = "hsi"
extint = "extint" # External interrupt

[default.extend-identifiers]
celcius = "celcius" # Until embedded-aht20 is fixed

[files]
extend-exclude = ["doc/*.svg", "src/riot-rs-rp/src/cyw43/firmware/README.md"]
