[package]
name = "nrf52840-mdk"
version = "0.1.0"
authors = ["Kaspar Schleiser <kaspar@schleiser.de>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m-rt.workspace = true
cortex-m.workspace = true

riot-rs-rt.workspace = true

nrf52840-hal.workspace = true
nrf52 = { path = "../nrf52" }
