[package]
name = "microbit-v2"
version = "0.1.0"
authors = ["Kaspar Schleiser <kaspar@schleiser.de>"]
edition = "2021"

[dependencies]
cortex-m-rt.workspace = true
cortex-m.workspace = true

riot-rs-rt.workspace = true

nrf52 = { path = "../nrf52", features = [ "nrf52840" ] }
