[package]
name = "stm32"
version = "0.1.0"
license.workspace = true
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(context = "stm32h7b0")'.dependencies]
ariel-os-embassy = { path = "../../ariel-os-embassy" }
ariel-os-debug = { path = "../../ariel-os-debug", features = ["rtt-target"] }
