[package]
name = "nrf52dk"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
cortex-m-rt.workspace = true
cortex-m.workspace = true

riot-rs-rt.workspace = true

nrf52832-hal.workspace = true
nrf52 = { path = "../nrf52" }
