[package]
name = "nrf52840dk"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
cortex-m.workspace = true
cortex-m-rt.workspace = true

riot-rs-debug.workspace = true
riot-rs-rt.workspace = true

nrf52 = { path = "../nrf52", features = ["nrf52840"] }
