[package]
name = "nrf51"
version = "0.1.0"
authors = ["Kaspar Schleiser <kaspar@schleiser.de>"]
license.workspace = true
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ariel-os-debug = { workspace = true }
ariel-os-rt = { path = "../../ariel-os-rt" }
nrf51-pac = { version = "0.12.2", features = ["rt"] }
