[package]
name = "embassy-http-server"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
publish = false

[dependencies]
riot-rs = { path = "../../src/riot-rs", features = [ "time", "usb_ethernet"] }
riot-rs-boards = { path = "../../src/riot-rs-boards" }
embassy-executor = { workspace = true, default-features = false }
embassy-sync = { workspace = true }
embassy-time = { workspace = true, default-features = false }
linkme.workspace = true
embassy-net = { workspace = true, features = ["tcp"] }
embedded-io-async = "0.6.0"
httparse = { version = "1.8.0", default-features = false }
picoserve = "0.3.0"
static_cell = { workspace = true }
