[package]
name = "nrf52840dk"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
cortex-m.workspace = true
cortex-m-rt.workspace = true

ariel-os-debug.workspace = true
ariel-os-rt.workspace = true

nrf52 = { path = "../nrf52", features = ["nrf52840"] }
