[book]
authors = ["Kaspar Schleiser"]
language = "en"
multilingual = false
src = "src"
title = "RIOT-rs manual"

[output.html]
git-repository-url = "https://github.com/future-proof-iot/RIOT-rs"
edit-url-template = "https://github.com/future-proof-iot/RIOT-rs/edit/master/book/{path}"
