[package]
name = "dwm1001"
version = "0.1.0"
authors = ["Kaspar Schleiser <kaspar@schleiser.de>"]
license.workspace = true
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m-rt.workspace = true
cortex-m.workspace = true

ariel-os-debug.workspace = true
ariel-os-rt = { path = "../../ariel-os-rt" }

nrf52 = { path = "../nrf52", features = ["nrf52832"] }
