[package]
name = "st-nucleo-wb55"
version = "0.1.0"
authors = ["Kaspar Schleiser <kaspar@schleiser.de>"]
license.workspace = true
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embassy-stm32 = { workspace = true, features = ["stm32wb55rg"] }
riot-rs-debug = { workspace = true, features = ["rtt-target"] }
riot-rs-stm32 = { workspace = true, features = ["stm32-rng", "stm32-usb"] }
riot-rs-rt.workspace = true
